### ISSUE TITLE
v5 tracking issue (v2 addon)

### ISSUE THREAD

**Issue by nickschot** [nickschot/ember-mobile-menu#799]
- [x] https://github.com/nickschot/ember-mobile-menu/pull/778
- [x] https://github.com/nickschot/ember-mobile-menu/pull/779
- [x] Replace ember-could-get-used-to-this with ember-resources https://github.com/nickschot/ember-mobile-menu/pull/776
- [x] Clean up dependencies & add proper peer dependencies (widen ranges where possible)
- [x] https://github.com/nickschot/ember-mobile-menu/pull/800
- [x] https://github.com/nickschot/ember-mobile-menu/pull/801
- [x] Replace ember-legacy-built-in-components based link-to component with another approach https://github.com/nickschot/ember-mobile-menu/pull/821
- [x] Update documentation regarding new CSS approach https://github.com/nickschot/ember-mobile-menu/pull/822

Nice-to-have:
- [x] Revisit to see if we can still support ember-source 3.28

**Comment by nickschot** [comment]
First pre-release v5.0.0-0 with the initial v2 conversion and SCSS replacement was released last week.
